/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Duplicatrchar;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void duplicateChar(){
        Duplicate testDuplicate=new Duplicate();

        String testString1="The quick brown fox jumps over the lazy dog";
        assertEquals(false,testDuplicate.isDuplicateChar(testString1));

        String testString2="I love cats";
        assertEquals(true,testDuplicate.isDuplicateChar(testString2));

    }
}
