/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LinkedList <Integer> testList=new LinkedList<>();
        testList.append(1);
        testList.append(2);
        testList.append(3);
        testList.append(4);
       // System.out.println(testList.head.value);
        testList.inserBeforeee(11,10);
        testList.insertAAfter(4,33);
       // testList.swappinList(2);
       // testList.reversee();


        System.out.println(testList.toString());
        System.out.println(new App().getGreeting());
    }
}
