/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Duplicatrchar;

import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        String testString="The quick brown fox jumps over the lazy dog";
        System.out.println(isDuplicateChar(testString));
    }


    public static boolean isDuplicateChar(String sentence){
        HashMap<Character,Character> hashMap=new HashMap<Character,Character>();
        String sentence2=sentence.toLowerCase();

        for (int i = 0; i < sentence2.length(); i++) {
            char lestter=sentence2.charAt(i);

            if(hashMap.containsValue(sentence2.charAt(i))){

                return false;
            }
           if(lestter != ' '){
               hashMap.put( sentence2.charAt(i), sentence2.charAt(i));
           }
        }
        return true;
    }
}
