/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch13;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Validatebrackets test=new Validatebrackets();
        String testOne="()[[Extra Characters]]";
        System.out.println( test.brackets(testOne));;
        String testTwo="[({}]";
        System.out.println( test.brackets(testTwo));


        System.out.println(new App().getGreeting());
    }
}
