/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

    }
    @Test void  insertTest(){

        Insertionsort insertTest=new Insertionsort();

        int[]  emptyArr = {};
        assertEquals(emptyArr, insertTest.insertionSort(emptyArr));


        int[]  oneElementArr = {8};
        assertEquals("[8]", Arrays.toString(insertTest.insertionSort(oneElementArr)));


        int[]  regularArr = {8,4,23,42,16,15};
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(insertTest.insertionSort(regularArr)));


        int[]  ReverseSortedArr = {20,18,12,8,5,-2};
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(insertTest.insertionSort(ReverseSortedArr)));


        int[]  FewUniquesArr = {5,12,7,5,5,7};
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(insertTest.insertionSort(FewUniquesArr)));


        int[]  NearlySortedArr = {2,3,5,7,13,11};
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(insertTest.insertionSort(NearlySortedArr)));
    }
}
