/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftJoins;

import java.util.ArrayList;
import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        HashmapLeftJoinClass hashmapLeftJoinClass =new HashmapLeftJoinClass();

        HashMap hashMap=new HashMap();
        hashMap.put("keyOne","one");
        hashMap.put("keyTow","tow");
        hashMap.put("keyThree","three");
        hashMap.put("keyFour","four");

        HashMap hashMapTow=new HashMap();
        hashMapTow.put("keyOne","not one");
        hashMapTow.put("keyTow","not tow");
        hashMapTow.put("keyThree","not three");
        hashMapTow.put("Not exist ","");

        System.out.println(hashmapLeftJoinClass.hashMapLeftJoinFunction(hashMap,hashMapTow));

        System.out.println(new App().getGreeting());
    }

}
