/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;


import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        QuickSort quickSort=new QuickSort();

        int [] testArr={10,5,-2,11};

        ;
        System.out.println(Arrays.toString(quickSort.quickSortFunction(testArr,0, testArr.length-1)));

    }
}
