/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void  testQuickSort(){
        QuickSort quickSort=new QuickSort();
        int [] arr={1,4,5,2};
        int[] res={1,2,4,5};
        assertEquals(Arrays.toString(res),Arrays.toString(quickSort.quickSortFunction(arr,0,arr.length-1)));
    }
}