/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge10;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        pseudoqueue <Integer> pse1=new pseudoqueue<>();
     //   pse1.enqueue(1);
     //   System.out.println(pse1.stack1.top.value);
      //  Node newNode=pse1.dequeue();
        Node nnewNode2=pse1.dequeue();
       // System.out.println(newNode.value);
        System.out.println(nnewNode2.value);


    }
}
