/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge10;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Stack <Integer> newstack=new Stack<>();
        newstack.push(1);
//        newstack.push(2);
//        newstack.push(3);
       Node newNode= newstack.pop();
//        System.out.println(newstack.toString());
//        System.out.println(newstack.top.value);
        System.out.println(newNode.value);
        System.out.println(newstack.isEmpty());

        Queue <Integer> newqueue=new Queue<>();
//        newqueue.enqueue(1);
//        newqueue.enqueue(2);
//        newqueue.enqueue(3);
//        Node returnNode= newqueue.dequeue();

        System.out.println(newqueue.isEmpty());
        System.out.println(newqueue.toString());



        System.out.println(new App().getGreeting());
    }
}
