/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge12;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
//        Queue <Integer> nEw=new Queue<>();
//        nEw.enqueue(1);
//        System.out.println(nEw.toString());
//        AnimalShelter newAnimals=new AnimalShelter();
//        newAnimals.enqueue("cat");
//        System.out.println(newAnimals.cats.toString());
//        Node returnCat= newAnimals.dequeueCat();
//        System.out.println(returnCat.value);
//        System.out.println(new App().getGreeting());

        AnimalShelter animalTest = new AnimalShelter();
        animalTest.enqueue("Dog");
        animalTest.enqueue("dog");
        System.out.println(animalTest.countDog);
    }
}
