/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        String testHashmap="Be happy for this moment this moment is your lisfe";
        String returnValue=repeatedWord(testHashmap);
        System.out.println(returnValue);




        System.out.println(new App().getGreeting());
    }

    public static String repeatedWord(String sentence) {
      HashMap <String,String> hashTable = new HashMap<>();
        String[] allWords = sentence.toLowerCase().replace(",", "").split(" ");
        for (String word : allWords) {
            if (hashTable.containsKey(word)) return word;
            else hashTable.put(word, word);
        }
        return null;
    }
}
