/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge12;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void enqueueTest() {
        AnimalShelter animalTest = new AnimalShelter();
        animalTest.enqueue("Cat");
        assertEquals("cat",animalTest.cats.front.value);
        animalTest.enqueue("dog");
        assertEquals("dog",animalTest.dogs.front.value);
        animalTest.enqueue("cat");
        assertEquals("cat",animalTest.cats.front.value);

        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void dequeueTest() {
        AnimalShelter animalTest = new AnimalShelter();
        animalTest.enqueue("Cat");
        animalTest.enqueue("dog");
        Node testCat=animalTest.dequeueCat();
        assertEquals("cat",testCat.value);

        Node testDog=animalTest.dequeueDog();
        assertEquals("dog",testDog.value);


    }
    @Test void deqPreferTest() {
        AnimalShelter animalTest = new AnimalShelter();
        animalTest.enqueue("Cat");
        animalTest.enqueue("Cat");
        animalTest.enqueue("Cat");


        Node testPrefer=animalTest.deqPrefer();
        assertEquals("cat",testPrefer.value);

    }

    @Test void countTest() {
        AnimalShelter animalTest = new AnimalShelter();
        animalTest.enqueue("Cat");
        animalTest.enqueue("Cat");
        animalTest.enqueue("Cat");
        Node catTest= animalTest.dequeueCat();

        animalTest.enqueue("Dog");
        animalTest.enqueue("dog");
        System.out.println(animalTest.countDog);



      //  Node testPrefer=animalTest.deqPrefer();
        assertEquals(2,animalTest.countCat);
        assertEquals(2,animalTest.countDog);
    }







}
