/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackqueue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

    Stack <Integer> stack1=new Stack<>();
//    stack1.push(1);
//    stack1.push(2);
//    stack1.push(3);
//    stack1.pop();
//        boolean dcx=stack1.isEmpty();
//    System.out.println(dcx);
    //System.out.println(stack1.toString());
        Queue <Integer> queuee=new Queue<>();
//        queuee.enqueue(1);
//        queuee.enqueue(2);
//        queuee.enqueue(3);
//        queuee.enqueue(4);
//        Node removednode= queuee.dequeue();
//
//
//        System.out.println(queuee.toString());
      //  System.out.println(queuee.front.value);
        System.out.println(queuee.ieEmpty());

    }

}
