/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge11;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void pseudoQueuetest() {
     Pseudoqueue <Integer> testPsedu=new Pseudoqueue<>();
     testPsedu.enqueue(1);
     assertEquals(1,testPsedu.stack1.top.value);


     assertEquals(1,testPsedu.dequeue());

     testPsedu.enqueue(4);
     testPsedu.enqueue(5);
     testPsedu.dequeue();

     assertEquals(5,testPsedu.stack1.top.value);


    }



}
