/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package class05;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void emptylinkedlist(){
        Linkedlist<Integer> linklest1=new Linkedlist<Integer>();
        assertEquals("Null",linklest1.toString());
    }

    @Test void insertlinkedlist(){
        Linkedlist<Integer> linklest2=new Linkedlist<Integer>();
        linklest2.insert(1);
        assertEquals(true,linklest2.includes(1));
    }

    @Test void headlinkedlist(){
        Linkedlist<Integer> linklest3=new Linkedlist<Integer>();
        linklest3.insert(1);
        linklest3.insert(2);

        assertEquals(2,linklest3.head.value);
    }

    @Test void Multiplenodeslinkedlist(){
        Linkedlist<Integer> linklest4=new Linkedlist<Integer>();
        linklest4.insert(1);
        linklest4.insert(2);
        linklest4.insert(5);
        boolean checkmultiple=linklest4.includes(1) && linklest4.includes(2) &&linklest4.includes(5);


        assertEquals(true,checkmultiple);
    }

    @Test void inCludeslinkedlist(){
        Linkedlist<Integer> linklest5=new Linkedlist<Integer>();
        linklest5.insert(1);
        linklest5.insert(2);
        linklest5.insert(5);


        assertEquals(true,linklest5.includes(5));
    }

    @Test void notinCludeslinkedlist(){
        Linkedlist<Integer> linklest5=new Linkedlist<Integer>();
        linklest5.insert(1);
        linklest5.insert(2);
        linklest5.insert(5);


        assertEquals(false,linklest5.includes(6));
    }

    @Test void returnvalueslinkedlist(){
        Linkedlist<Integer> linklest5=new Linkedlist<Integer>();
        linklest5.insert(1);
        linklest5.insert(2);
        linklest5.insert(5);
        boolean checkmultiple=linklest5.includes(1) && linklest5.includes(2) &&linklest5.includes(5);


        assertEquals(true,checkmultiple);
    }







}
