/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Node <Integer>testNode=new Node(5);

        BinarySearch test =new BinarySearch(testNode);

        test.add(10);
        test.add(3);
        System.out.println(test.root.value);
        System.out.println(test.root.leftChild.value);
        test.add(4);
        System.out.println(test.root.leftChild.rightChild.value);
        System.out.println(new App().getGreeting());
    }
}
