/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import java.util.ArrayList;
import java.util.LinkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Node <Integer>testNode=new Node(1);

        BinarySearch test =new BinarySearch();
        test.root=testNode;

        System.out.println(test.getMax());
        test.add(5);
        test.add(7);
        test.add(3);
        test.add(14);
        test.add(8);

        ArrayList <Integer> returnBreath= test.breadthFirstTree(test.root);
      //  System.out.println(returnBreath);

        FizzBuzzTree tree = new FizzBuzzTree();
        tree.root = new KNode(1);
        tree.root.left = new KNode(3);
        tree.root.right = new KNode(2);
        tree.root.left.left = new KNode(5);
        tree.root.left.right = new KNode(88);
        tree.root.right.left = new KNode(15);
        tree.root.right.right = new KNode(50);
        System.out.println("Tree before Apply FizzBuzz function👇\n");
        tree.printPreorderA(tree.root);
        System.out.println("\n\nTree After Apply FizzBuzz function👇\n");
        tree.preorder(tree.root);
        System.out.println("\n_____________________________________________________________________________________________\n\n\n");



    }






    }
