/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import java.util.ArrayList;
import java.util.LinkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Node <Integer>testNode=new Node(1);
        Node <Integer> tesNode2=new Node<>(2);
        Treeintersection testSearch=new Treeintersection();

        BinarySearch test =new BinarySearch();
        BinarySearch test2 =new BinarySearch();
        test.root=testNode;
        test2.root=tesNode2;


        test.add(5);
        test.add(7);
        test.add(3);
        test.add(14);
        test.add(8);

        test2.add(5);
        test2.add(11);
        test2.add(3);

        test2.add(9);
        test2.add(10);

        ArrayList<Integer> testArray=new ArrayList<>();

        testArray=testSearch.duplicateValues(test,test2);
        System.out.println(testArray);

    }

}
