/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package class89;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test public void testempty(){
        Linkedlist <Integer> test0=new Linkedlist<>();
        Linkedlist <Integer> test1=new Linkedlist<>();
        Linkedlist <Integer> test2=new Linkedlist<>();
        test0.append(1);
        test0.append(10);
        test2.linkedlistzip(test0,test1);

        assertEquals(1,test2.head.value);
    }


    @Test public void testdifferentsizes(){
        Linkedlist <Integer> test0=new Linkedlist<>();
        Linkedlist <Integer> test1=new Linkedlist<>();
        Linkedlist <Integer> test2=new Linkedlist<>();
        test0.append(1);
        test0.append(10);
        test1.append(2);
        test1.append(3);
        test1.append(4);
        test2.linkedlistzip(test0,test1);

        assertEquals(2,test2.head.next.value);
    }

}
