/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void hashTAbleTest(){
        // Adding a key/value to your hashtable results in the value being in the data structure
        HashTable testTable = new HashTable<>();
        testTable.add("testValue", 10);
        assertEquals(10, testTable.get("testValue"));
        assertEquals("HashTable{hashTable=[null, null, null, null, null, null, null, null, null, null, Bucket{key=testValue, value=10}, null, null, null, null]}", testTable.toString());



        assertNull(testTable.get("mohammed"));

        testTable.add("A", "certain Value");
        testTable.add("second", "second Value");
        assertEquals("HashTable{hashTable=[null, null, null, null, null, Bucket{key=A, value=certain Value}, null, null, null, null, Bucket{key=second, value=second Value}, null, null, null, null]}", testTable.toString());

        assertEquals("second Value", testTable.get("second"));

        assertEquals(5, testTable.hash("A"));
        assertEquals(10, testTable.hash("second"));

    }

}
