/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftJoins;

import org.junit.jupiter.api.Test;

import java.util.HashMap;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testCode32(){
        HashmapLeftJoinClass hashmapLeftJoinClass =new HashmapLeftJoinClass();

        HashMap hashMap=new HashMap();
        hashMap.put("keyOne","one");
        hashMap.put("keyTow","tow");
        hashMap.put("keyThree","three");
        hashMap.put("keyFour","four");

        HashMap hashMapTow=new HashMap();
        hashMapTow.put("keyOne","not one");
        hashMapTow.put("keyTow","not tow");
        hashMapTow.put("keyThree","not three");
        hashMapTow.put("Not exist ","");

        HashMap hashMapResult=new HashMap();
        hashMapResult.put("keyThree"," three,not three ");
        hashMapResult.put("keyTow"," tow,not tow ");
        hashMapResult.put("keyOne"," one,not one ");
        hashMapResult.put("keyFour"," four,null ");
        assertEquals(hashMapResult, hashmapLeftJoinClass.hashMapLeftJoinFunction(hashMap,hashMapTow));

    }

}
