/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package class89;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Linkedlist <Integer> linkedlist1=new Linkedlist<>();
        linkedlist1.insert(1);
        // linkedlist1.insert(5);

//
        linkedlist1.append(5);
        linkedlist1.append(2);

      //  linkedlist1.reverse();
        boolean test1= linkedlist1.symettri();
     System.out.println(test1);

//     boolean cdgfs= linkedlist1.symettri();
//        System.out.println(cdgfs);


    }
}
