/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenge7;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   @Test public void testkgreator(){
       Linkedlist <Integer> teslist=new Linkedlist<>();
       teslist.append(1);
       teslist.append(2);
       teslist.append(3);
assertEquals(null,teslist.kthFromEnd(3));

   }


    @Test public void testksame(){
        Linkedlist <Integer> teslist=new Linkedlist<>();
        teslist.append(1);
        teslist.append(2);
        teslist.append(3);
        assertEquals(null,teslist.kthFromEnd(2));

    }

    @Test public void testknegativee(){
        Linkedlist <Integer> teslist=new Linkedlist<>();
        teslist.append(1);
        teslist.append(2);
        teslist.append(3);
        assertEquals(null,teslist.kthFromEnd(-1));

    }

    @Test public void onesize(){
        Linkedlist <Integer> teslist=new Linkedlist<>();
        teslist.append(1);

        assertEquals(1,teslist.kthFromEnd(0).value);

    }

    @Test public void kinMidlle(){
        Linkedlist <Integer> teslist=new Linkedlist<>();
        teslist.append(1);
        teslist.append(2);
        teslist.append(3);
        assertEquals(2,teslist.kthFromEnd(1).value);

    }



}
