/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void graphTest(){


        Graph myGraph = new Graph();
        assertNull(myGraph.toString());

        myGraph.addNode("8");
        assertEquals("[8]", myGraph.getNodes().toString());

        myGraph.addEdge("8", "8", 0);
        assertEquals("[8]", myGraph.getNeighbors("8").toString());
        assertEquals("{8=[8]}", myGraph.nodeList.toString());

        myGraph.addNode("5");
        myGraph.addEdge("8", "5", 70);
        assertEquals("[8, 5]", myGraph.getNeighbors("8").toString());
        assertEquals("[8]", myGraph.getNeighbors("5").toString());

        assertEquals("[5, 8]", myGraph.getNodes().toString());

        assertEquals("{5=[8], 8=[8, 5]}", myGraph.nodeList.toString());

        assertEquals(2, myGraph.size());
    }
}
